language: node_js

node_js:
  - node
  - 14
  - 12

branches:
  only:
    - master

cache: yarn

git:
  depth: false

script:
  - yarn format:check
  - yarn lint
  - yarn build
  - yarn test:coverage
  - yarn codecov

jobs:
  include:
    - stage: deploy
      if: branch = master
      node_js: node
      before_deploy:
        - if [ "$BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./release.sh compare_and_release; fi
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_TOKEN'
        skip_cleanup: true
        on:
          branch: master
