version: '3.3'

services:
  mssql:
    container_name: 'example-mssql'
    image: 'mcr.microsoft.com/mssql/server:2017-GA-ubuntu'
    ports:
      - '1433:1433'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Secret@123'

  app:
    network_mode: host
    container_name: 'example-app'
    build: .
